### PR TITLE
Initial Markdown Migration

### PR DESCRIPTION
**Pull request by v-anpasi**

### CODE REVIEW

**Comment by rowanmiller** [comment]
Looks like this has the `_site` directory being added, I think you want to add that to `.gitignore` right?

**Comment by v-anpasi** [comment]
@rowanmiller I am not familiar with a lot of the configuration details of docfx. If this folder needs to be removed we can take care of that at a later date.

**Comment by rowanmiller** [comment]
`_site` is the rendered output when you build the site locally. So it's build output.

**Comment by rowanmiller** [comment]
But yes, we can remove it later if you prefer

**Pull request merged**
