### PR TITLE
Update index.rst to clarify .NET 4.5.1 requirement

### PR DESCRIPTION
**Pull request by ErikEJ**
Bump up to .NET 4.5.1 required

### CODE REVIEW

**Comment by natemcmaster** [comment]
LGTM.

**Comment by rowanmiller** [comment]
I think the current release does work on .NET 4.5 right? I've been bumping the min-version to 4.5.1 as I work on the updates for RC1. It's fine to leave this in, but master is for the current stable release.

**Comment by natemcmaster** [comment]
I haven't tested. I thought we bumped to 4.5.1 before beta8.

**Comment by ErikEJ** [comment]
I have never tested on a Vanilla 4.5 Windows 8.0 machine with VS 2012. I think the required Nuget tools in VS do not work with VS 2012 anyway

**Pull request merged**
