### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by msawczyn**
Added tool entry for Entity Framework Visual Editor (https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner)

### CODE REVIEW

**Comment by divega** [comment]
@msawczyn Thanks for this PR! How do I specify that I want the code generated to be for EF Core? I am getting EF6 classes generated instead. When I try to change the "Entity Framework Version" property on the file to EF Core, I get a message dialog saying "EF Core currently only supports Table-Per-Hierarchy inheritance strategy". When I close the dialog, the property value goes back to EF6. I should clarify that the model only contains one entity (so no inheritance).

**Comment by divega** [comment]
@msawczyn friendly ping... I would love to merge this but first I want to be sure I understand how to make it work with EF Core.

**Comment by divega** [comment]
I tried this again today and I was able to switch to EF Core code generation before I started adding entities to the model.

**Comment by msawczyn** [comment]
@divega -- I just saw this. No clue why github didn't drop me an email when you did the mention back in June, but my apologies nonetheless. I'm really not the uncommunicative fool you probably think I am \<g\>.

The message you initially got was one of those "as-designed" behaviors ... as-designed, but unclear. You had an inheritance strategy set that was something other than table-per-hierarchy, so when you tried to toggle over to EFCore, it complained that it couldn't do that with the indicated inheritance strategy.

Only the message really wasn't clear, and you're not the first one to bring it up.

So I made a change a few versions back that, since only one inheritance strategy is supported, simply changed it when you ticked the model over to EFCore. Kind of felt a bit heavy handed to do that but, hey, it's all you can do anyway, right?

When other inheritance types are supported, I'll make the change that stops that behavior, but it does seem to have made folks a bit less confused, so I guess it was the right thing to do.

Thanks for the mention, and sorry again that I didn't see your comment back when you had made it.

**Comment by divega** [comment]
@msawczyn no worries :smile: Thanks again for the PR and great to learn about your tool!

**Pull request merged**
