### PR TITLE
creation of data annotation page

### PR DESCRIPTION
**Pull request by MarcAir**
creating data annotation page

### CODE REVIEW

**Comment by bradygaster** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/core/modeling/dataannotations.md](https://github.com/MarcAir/EntityFramework.Docs/blob/MarcAir-patch-1/entity-framework/core/modeling/dataannotations.md) | :warning:Warning | | [Details](#user-content-entity-framework/core/modeling/dataannotations.md)

<a name="entity-framework/core/modeling/dataannotations.md"></a>
### [entity-framework/core/modeling/dataannotations.md](https://github.com/MarcAir/EntityFramework.Docs/blob/MarcAir-patch-1/entity-framework/core/modeling/dataannotations.md)
 - **Line 35**: **[Warning]** Invalid file link:(~/core/required-optional.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C7%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201612072022545276-312%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rowanmiller** [comment]
It's not clear to me exactly what the purpose of this page is. It shows a few data annotations, but only 1 of the 3 means anything to EF (`[Required]`). The EF Core docs are centered around what type of configuration you want to do, and then cover conventions, annotations, and fluent API for that topic. This page feels incomplete and not inline with how the docs are organized.

**Comment by MarcAir** [comment]
thanks for the feedback rowan.
i do agree with you that the page is more of a snippit that a full page. 
i was trying to enrich the docuemntation for creating a model but was not fully sure where to include the detail.
perhaps i should include this as an addition to the model creation page under data annotation? thoughts?

**Comment by rowanmiller** [comment]
@MarcAir what is the key piece of information that you are trying to get across here? `[Display]` and `[DataType]` are not used from an EF perspective. `[Required]` is covered under https://docs.microsoft.com/en-us/ef/core/modeling/required-optional#data-annotations.

**Comment by MarcAir** [comment]
i see yes you are right EF doesn't use these decorations, its more that it is something then that should be included in another set of documentation like aspnet/mvc as this decoration is very helpful for fields in web.

**Pull request closed without merging**
