### PR TITLE
Updates to Devart provider info

### PR DESCRIPTION
**Pull request by User235**

### CODE REVIEW

**Comment by rowanmiller** [comment]
@User235 do you work on the devart provider? If so, can you confirm that the provider does now support the 1.0.0 release? I couldn't find anything in the docs to indicate this.

**Comment by User235** [comment]
Hi Rowan,

Entity Framework 1.0 was supported on July 7, 2016 in all Devart Entity Framework providers (database and clouds):

https://www.devart.com/dotconnect/oracle/revision_history.html

This info is indicated only on the revision page of each provider

Best Regards,
Alexey Gryaznov
Marketing Manager
Devart

**Comment by rowanmiller** [comment]
Thanks for confirming... and thanks for the pull request! From the user name I wasn't sure if you worked at Devart or not 😄.

**Comment by User235** [comment]
Rowan,

Sorry for the confusion, this account is only for editing Entity Framework docs :) Thank you for the help!

Best Regards,
Alexey Gryaznov
Marketing Manager
Devart

**Pull request merged**
