### PR TITLE
Update breaking-changes.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Internal review URL](https://review.docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes?branch=pr-en-us-1597)

### CODE REVIEW

**Comment by ajcvickers** [comment]
@Rick-Anderson @divega These changes made it into master (see https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md) but aren't on the docs site: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes

Any idea what's going on? I need to reference the doc when talking to customers about preview 7 issues.

**Comment by Rick-Anderson** [comment]
You need to merge master to live. I can do that, but @divega  normally does that

**Comment by Rick-Anderson** [comment]
Are they in https://github.com/aspnet/EntityFramework.Docs/blob/live/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md

**Comment by Rick-Anderson** [comment]
@ajcvickers  history shows the last update in not in the live branch.

**Comment by Rick-Anderson** [comment]
See #1601

**Comment by divega** [comment]
Done.

**Comment by divega** [comment]
LOL @Rick-Anderson you beat me to it, but git didn't complain.

**Comment by ajcvickers** [comment]
Thanks guys!

**Pull request merged**
