### PR TITLE
Add info about Sapient Guardian MySQL provider

### PR DESCRIPTION
**Pull request by rowanmiller**
cc @how02 in case you have any feedback on the content

### CODE REVIEW

**Comment by how02** [comment]
Looks good to me, @SapientGuardian anything to add ?

**Comment by SapientGuardian** [comment]
I wouldn't say "Sapient Guardian Project", SapientGuardian is really just my handle. You could say that it's a companion to SapientGuardian's MySQL connector (https://github.com/SapientGuardian/mysql-connector-net-netstandard) if you wanted, or just leave that part out entirely. I'm fine with either.

**Comment by rowanmiller** [comment]
Closing this as we are porting the docs to a new system. Will push changes in the new format once the port is complete.

**Comment by rowanmiller** [comment]
Added in https://github.com/aspnet/EntityFramework.Docs/commit/61423f87981232ed5f7ae220312b07d149ed3b50

**Pull request closed without merging**
