### PR TITLE
I thought Keyless Entity Types were added in 3.0??

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by smitpatel** [comment]
@SimonCropp - Thank you.

**Comment by divega** [comment]
@smitpatel, @SimonCropp I am not sure this is better than what we had before. Query types existed since 2.1. Keyless entities is mostly a rename of the same concept to make the API easier to use and understand.

**Comment by smitpatel** [comment]
We should rephrase the statement then. Earlier was also somewhat ambiguous.

**Comment by divega** [comment]
Done.

**Pull request merged**
