### PR TITLE
Update ASP.NET Core docs link

### PR DESCRIPTION
**Pull request by guardrex**
Noticed this in passing.

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/core/get-started/aspnetcore/index.md](https://github.com/guardrex/EntityFramework.Docs/blob/patch-1/entity-framework/core/get-started/aspnetcore/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C9%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201709090548108574-474%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ajcvickers** [comment]
Both URLs resolve to the same location, so closing, but thanks anyway!

**Comment by guardrex** [comment]
@ajcvickers It's a redirect. We don't use that address any longer.

**Comment by scottaddie** [comment]
@danroth27 What's your URL preference? My understanding is that "https://docs.microsoft.com/aspnet/core/" is preferred over "docs.asp.net".

**Comment by danroth27** [comment]
I actually like docs.asp.net better. It's easier to remember.

**Comment by mairaw** [comment]
However, none of the options work for offline books if we're generating those for EF. You need relative paths ofr that.

**Pull request closed without merging**
