### PR TITLE
Improve generated property docs

### LINKED ISSUE #122: RC2: Update docs generated property docs since triggers will be supported
In RC1 you can't really setup `ValueGeneratedOnAddOrUpdate` for properties other than `ROWVERSION` because you can't use triggers (due to aspnet/EntityFramework#1441).

We should update the following docs with examples once they work end-to-end:
- generated-properties.rst
- explicit-generated-values.rst

### PR DESCRIPTION
**Pull request by rowanmiller**
The main changes that need review are in entity-framework/core/saving/explicit-values-generated-properties.md 

cc @AndriySvyryd for review

Resolves #122

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C31%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201701312123539936-344%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C1%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201702011838154129-344%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rowanmiller** [comment]
I'm going to merge, as the current docs are incorrect, but feel free to give feedback and I will address in a follow up commit 😄

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C1%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201702011841218158-344%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
