### PR TITLE
Cascade delete samples show incorrect id (fix for #899)

### LINKED ISSUE #899: Examples: Second Post should have ID = 2
```
Blog '1' is ...
   Post '1' is ...
   Post '1' is ...
```

should be:

```
Blog '1' is ...
   Post '1' is ...
   Post '2' is ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

### PR DESCRIPTION
**Pull request by nikitasavinov**
Fixes #899 :)

### CODE REVIEW

**Comment by divega** [comment]
cc @ajcvickers in case the sample program has a bug that we can fix.

**Comment by divega** [comment]
@nikitasavinov thanks for the PR! Would you mind signing the CLA?

**Comment by divega** [comment]
@nikitasavinov in case you are interested, we would like to look at the sample code (linked from the page) that was used to generate the outputs you are fixing in case it has a bug. If you decide to only fix the outputs, we will keep #899 open to track looking at the sample code at a later point.

**Comment by nikitasavinov** [comment]
Thanks @divega, I should have noticed the link to the sample project. Anyway, just pushed a fix for a sample project as well.

**Comment by divega** [comment]
@ajcvickers can you please review the change to the sample code? Feel free to merge if you approve.

**Pull request merged**
