### PR TITLE
:arrow_up: Get Started Full .NET => RC1

### PR DESCRIPTION
**Pull request by rowanmiller**

### CODE REVIEW

**Comment by ErikEJ** [comment]
Will the rc1 package names be "rc1-final" ?

**Comment by smitpatel** [comment]
@ErikEJ - Yes. Check aspnet/Announcements#97

**Comment by ErikEJ** [comment]
Thanks - so https://www.myget.org/gallery/aspnetrc1 !

**Comment by natemcmaster** [comment]
:shipit:

**Pull request merged**
