### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Search EF and not all of docs.microsoft.com

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/docfx.json](https://github.com/aspnet/EntityFramework.Docs/blob/Rick-Anderson-patch-1/entity-framework/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C7%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201710070606381671-511%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KWni3LdkyR9qDZH%2FWYDNMujPo%2FwST%2B7k83DgCh69LZo%3D&st=2017-10-07T06%3A03%3A12Z&se=2017-10-08T06%3A13%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@EisenbergEffect please review

**Comment by Rick-Anderson** [comment]
>Is foo a real thing?

copy/paste from what @EisenbergEffect did on my repo. I have no idea what it's for.

**Comment by EisenbergEffect** [comment]
I actually have no idea what `_navPath` and `_navRel` are. Did I do something on one of your repos? I don't recall that. The `searchScope` is correct though you might want to make it into a more human readable value, such as "Entity Framework".

**Comment by Rick-Anderson** [comment]
@divega  removed `_navPath` and `_navRel`  and changed EF to Entity Framework.

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/docfx.json](https://github.com/aspnet/EntityFramework.Docs/blob/Rick-Anderson-patch-1/entity-framework/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C8%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201710080357028655-511%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bgJYsIKU561xLtHH8yzS0GpNb8Xuo11KLbsiF8citHA%3D&st=2017-10-08T03%3A52%3A49Z&se=2017-10-09T04%3A02%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@divega  let me know when you merge live and I'll test.

**Comment by divega** [comment]
@Rick-Anderson done.

**Pull request merged**
