### PR TITLE
Update Pomelo Provider

### PR DESCRIPTION
**Pull request by Kagamine**

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/core/providers/pomelo/index.md](https://github.com/Kagamine/EntityFramework.Docs/blob/patch-3/entity-framework/core/providers/pomelo/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C4%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201707040052081228-417%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Kagamine** [comment]
@divega

**Comment by Kagamine** [comment]
Thanks

**Comment by divega** [comment]
Thanks @Kagamine.

**Pull request merged**
