### PR TITLE
:memo: Getting Started on UWP

### PR DESCRIPTION
**Pull request by rowanmiller**
First cut at getting started on UWP
Staged: http://ef.readthedocs.org/en/staging/getting-started/uwp.html
I'm still sorting out why syntax highlighting isn't working on the page

### CODE REVIEW

**Comment by rowanmiller** [comment]
cc @bricelam @natemcmaster to see if there is anything else you hit that you think should be called out as a known issue etc.

**Comment by natemcmaster** [comment]
Yes, there are issues in SQLite. See https://github.com/aspnet/EntityFramework.Docs/pull/26. There may be others specific to UWP.

**Comment by rowanmiller** [comment]
@natemcmaster think I have those covered already (the Startup.cs one doesn't exists because UWP uses Package Manager Console rather than DNX)

**Comment by natemcmaster** [comment]
:shipit: (assuming you've walked through the steps with VS RTM and it works). I didn't actually try it, but it looks right.

**Comment by rowanmiller** [comment]
Yep I wrote it as I was building the sample :smile:

**Pull request merged**
