### PR TITLE
Update limitations.md

### PR DESCRIPTION
**Pull request by dazinator**
Updated RenameIndex support as per: https://github.com/aspnet/EntityFrameworkCore/pull/9905

### CODE REVIEW

**Comment by bricelam** [comment]
Yes, it was only added for 2.1. Versioning this table sounds like a good plan to me.

**Comment by divega** [comment]
@bricelam then does the table below look correct? 

I am ok with the version only appearing if it is != 1.0, and also putting the version number directly in the "Supported?" column. Essentially, make the bable below look whatever way you want and I will check it in :grin:

| Operation            | Supported? | Requires version |
| -------------------- | ---------- |-|
| AddColumn            | ✔          | 1.0 |
| AddForeignKey        | ✗          ||
| AddPrimaryKey        | ✗          ||
| AddUniqueConstraint  | ✗          ||
| AlterColumn          | ✗          ||
| CreateIndex          | ✔          | 1.0 |
| CreateTable          | ✔          | 1.0 |
| DropColumn           | ✗          ||
| DropForeignKey       | ✗          ||
| DropIndex            | ✔          | 1.0 |
| DropPrimaryKey       | ✗          ||
| DropTable            | ✔          | 1.0 |
| DropUniqueConstraint | ✗          ||
| RenameColumn         | ✔          | 2.1 |
| RenameIndex          | ✔          | 1.0 |
| RenameTable          | ✔          | 1.0 |

**Comment by bricelam** [comment]
That's correct.

Side notes:
- We made EnsureSchema and DropSchema no-op in 2.0.
- Insert, Update & Delete operations were added in 2.0

**Comment by divega** [comment]
@dazinator @bricelam I ended up taking the update in #633. Thanks!

**Pull request closed without merging**
