### PR TITLE
	Update full-dotnet.rst

### PR DESCRIPTION
**Pull request by ejsd1989**
Modified the changes i committed in Update full-dotnet.rst #52 to be in .. note:: boxes as requested by rowanmiller.

### CODE REVIEW

**Comment by rowanmiller** [comment]
@ejsd1989 the way you have `..note::` directives repeated results in multiple boxes showing up. Can you consolidate down to a single box with the tip in it. It's always a good idea to build the docs and check the rendered page before submitting a pull request.

render

I also need you to rebase this one on the latest changes in the `master` branch.

**Comment by rowanmiller** [comment]
BTW if you'd rather just do a new PR off master, rather than rebasing, that is fine too.

**Comment by ejsd1989** [comment]
Ahh i see. thanks for the heads up. I will look into it

**Comment by rowanmiller** [comment]
Closing as there has not been any activity. Feel free to send a new PR with requested updates.

**Pull request closed without merging**
