### PR TITLE
Merge to live...

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by smitpatel** [comment]
Something wrong with this merge. Master & live seems to be diverging even though they both have same changes.

**Comment by AndriySvyryd** [comment]
The PR was likely rebased instead of merged.

**Comment by bricelam** [comment]
Reset live to master and force-push it

**Comment by bricelam** [comment]
I tried to salvage it with a merge at the time, but yeah... that will just cause merge commits forevermore

**Comment by smitpatel** [comment]
I merged live to master and created PR to merge master to live to settle the matter.

**Pull request merged**
