### PR TITLE
🐛 Clarify VS2017 RC4 needed for ASP.NET Core walkthroughs

### PR DESCRIPTION
**Pull request by MaherJendoubi**
React to https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#feb7

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C12%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201702121316488613-349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C12%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201702121357016887-349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rowanmiller** [comment]
I'm curious about this one, did you see issues using RC3? I went thru the tutorials with RC3 and they worked.

BTW the changes to the code files aren't something we'd want to take. The goal is to have the code be exactly what you'd get following the steps of the tutorial, so we don't do any code cleanup etc.

**Comment by MaherJendoubi** [comment]
@rowanmiller I didn't see any issues using RC3.

**Comment by rowanmiller** [comment]
I'll close this one out then, as I think RC3 is a fine pre-req (although maybe we should say "or newer version").

**Comment by Rick-Anderson** [comment]
>"or newer version").

I think we generally say "or higher"
cc @tdykstra

**Comment by tdykstra** [comment]
Style guide recommends "earlier" or "later" rather than "lower" or "higher"

**Comment by rowanmiller** [comment]
Thanks! Given we are so close to RTM, I will probably just remove the RC3/RC4 part.

**Comment by MaherJendoubi** [comment]
@tdykstra where could I find the Style guide?

**Comment by tdykstra** [comment]
@MaherJendoubi It isn't public yet, but we're working on making it public.

**Comment by MaherJendoubi** [comment]
@tdykstra thank you!

**Comment by ErikEJ** [comment]
@MaherJendoubi There are some guidlines here: https://github.com/dotnet/docs/blob/master/styleguide/voice-tone.md

**Comment by MaherJendoubi** [comment]
@ErikEJ Thanks a lot!

**Comment by tdykstra** [comment]
@MaherJendoubi That one is public but it is fairly general and limited in scope.  The more detailed one is still to come.

**Pull request closed without merging**
