### PR TITLE
:memo: Initial page for DB2 provider

### PR DESCRIPTION
**Pull request by rowanmiller**

### CODE REVIEW

**Comment by rowanmiller** [comment]
@PrashanthIBM can you take a quick look over this and see if it looks good. Also, do you have a place we can point folks to report bugs.

**Comment by rowanmiller** [comment]
@PrashanthIBM thanks for the review. Regarding 2b, sounds like you are saying it only supports `DB2 for z/OS` at the moment right? So I will just list that.

**Comment by rowanmiller** [comment]
> DNX/ASP.NET 5 (dnx451 only) --> remove this line. We only support FULL .Net(4.5.1 onwards) . 

Full .NET is all you need to support dnx451 (but you don't support dnxcore50)

**Comment by PrashanthIBM** [comment]
@rowanmiller , currently we support only DB2 for z/OS, but we have a readme.txt file which will be part of the package and we keep updating our latest supported servers in the readme.txt with each release and also we have blog link for Latest Updates on EF7. Just to avoid frequent doc update requests, we wanted to just mention "IBM Data Servers" under the database supported list.

**Comment by rowanmiller** [comment]
Page is now live - https://docs.efproject.net/en/latest/providers/ibm/index.html.

If you want future updates, feel free to send a pull request. You won't need to sign a contributor agreement for small doc changes.

**Comment by PrashanthIBM** [comment]
@rowanmiller , Thanks a lot :)

**Comment by rowanmiller** [comment]
@PrashanthIBM can you email me so that we can discuss coordination of RC2

**Comment by PrashanthIBM** [comment]
@rowanmiller replied to your email id.

**Pull request merged**
