### PR TITLE
Update new-db.md

### PR DESCRIPTION
**Pull request by badersur**

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/badersur/EntityFramework.Docs/blob/patch-1/entity-framework/core/get-started/aspnetcore/new-db.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C10%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201709101311235214-475%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bradygaster** [comment]
### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C9%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201710092153344014-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2OPgZM1IzS4TjlvMC0IoohZzvuAPYCD6EileSbvBd4w%3D&st=2017-10-09T21%3A49%3A17Z&se=2017-11-09T21%3A54%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by divega** [comment]
Thanks @badersur for the fix. I have committed your change directly to master in 94210d1352f06559a9c4dbcc784b7e0897ad21cd and made some additional changes in dee310809c304c19dff8c4e58e68fda079ae2f7f. Closing as I won't be able to mark this as merged.

**Comment by badersur** [comment]
You're welcome. I don't understand how my changes went to master while my PR is closed! seems magic to me!

**Comment by divega** [comment]
@badersur I think it might have been a consequence of re-targeting your PR to be based on master (if I remember correctly it was originally based on the live branch). This apparently made GitHub somehow lose tack that the contents of your PR got merged.

**Pull request closed without merging**
