### PR TITLE
Update dotnet-ef doc

### PR DESCRIPTION
**Pull request by natemcmaster**
Update document including explanation of workarounds and common errors.

### CODE REVIEW

**Comment by lajones** [comment]
Looks good to me, but perhaps @rowanmiller should review the error messages. But just to check, is it true that e.g. a `-c` option just after `dotnet ef` will _not_ clash with a `-c` option specified after the command? So e.g. `dotnet ef -c <some_configuration> some_command -c <some_other_option>` will work correctly?

**Comment by natemcmaster** [comment]
Correct, these parameters don’t clash. Order matters though. This is something we want to revisit in https://github.com/aspnet/EntityFramework/issues/5188

**Comment by lajones** [comment]
OK - as far as I'm concerned :shipit:

**Comment by rowanmiller** [comment]
:shipit:

**Pull request merged**
