### PR TITLE
Sentence completion

### PR DESCRIPTION
**Pull request by OOberoi**
Added fillers to complete the sentence. Kindly review!

### CODE REVIEW

**Comment by ajcvickers** [comment]
@OOberoi The sentence seems correct to me before your changes and not after. Can you provide a few more details as to the purpose of this change?

**Comment by OOberoi** [comment]
Hey Arthur, I read the description for "Missing property values" couple more times. Even though, you could pass it as is, however, I would word it as the following with minor changes. That being said, I wholeheartedly and respectfully would leave it at your discretion.

"In the previous example, we removed the "TrackingNumber" property from the order object. Because of how indexing works in Cosmos DB, queries that reference the missing property somewhere else, than in the projection, it could return unexpected results. For example:

**Comment by ajcvickers** [comment]
@OOberoi We reviewed as a team and agreed to keep the current text. Thanks anyway!

**Comment by OOberoi** [comment]
No worries at all. Thanks Arthur!

**Pull request closed without merging**
