### PR TITLE
Remove Sapient Guardian provider

### PR DESCRIPTION
**Pull request by caleblloyd**
Sapient is showing a recommendation for it's users to switch to Pomelo for a MySql provider:

https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql

It also looks like there's not an active maintainer working on a 2.0.0 upgrade:

https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/56

### CODE REVIEW

**Comment by bradygaster** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-)
[entity-framework/core/providers/sapient-guardian/index.md](https://github.com/caleblloyd/EntityFramework.Docs/blob/f_remove_sapient/entity-framework/core/providers/sapient-guardian/index.md) | :white_check_mark:Succeeded | |
[entity-framework/toc.md](https://github.com/caleblloyd/EntityFramework.Docs/blob/f_remove_sapient/entity-framework/toc.md) | :white_check_mark:Succeeded | |

<a name=""></a>
### []()
 - **[Warning]** The log line content &#39;W:\l5sz-s\.openpublishing.build.ps1&#39; can&#39;t be converted to log item. Details: {&quot;message&quot;:&quot;Inline code snippet is only allowed inside tables.&quot;,&quot;source&quot;:&quot;Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.BuildConceptualDocument&quot;,&quot;file&quot;:&quot;entity-framework/64&quot;,&quot;line&quot;:&quot;InvalidInlineCodeSnippet&quot;,&quot;date_time&quot;:&quot;2017-06-13T19:09:36.0432714Z&quot;,&quot;message_severity&quot;:&quot;warning&quot;}
 - **[Warning]** The log line content &#39;W:\l5sz-s\.openpublishing.build.ps1&#39; can&#39;t be converted to log item. Details: {&quot;message&quot;:&quot;Inline code snippet is only allowed inside tables.&quot;,&quot;source&quot;:&quot;Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.BuildConceptualDocument&quot;,&quot;file&quot;:&quot;entity-framework/82&quot;,&quot;line&quot;:&quot;InvalidInlineCodeSnippet&quot;,&quot;date_time&quot;:&quot;2017-06-13T19:09:36.262022Z&quot;,&quot;message_severity&quot;:&quot;warning&quot;}
 - **[Warning]** The log line content &#39;W:\l5sz-s\.openpublishing.build.ps1&#39; can&#39;t be converted to log item. Details: {&quot;message&quot;:&quot;Inline code snippet is only allowed inside tables.&quot;,&quot;source&quot;:&quot;Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.BuildConceptualDocument&quot;,&quot;file&quot;:&quot;entity-framework/64&quot;,&quot;line&quot;:&quot;InvalidInlineCodeSnippet&quot;,&quot;date_time&quot;:&quot;2017-06-13T19:09:36.2776488Z&quot;,&quot;message_severity&quot;:&quot;warning&quot;}
 - **[Warning]** The log line content &#39;W:\l5sz-s\.openpublishing.build.ps1&#39; can&#39;t be converted to log item. Details: {&quot;message&quot;:&quot;Inline code snippet is only allowed inside tables.&quot;,&quot;source&quot;:&quot;Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.BuildConceptualDocument&quot;,&quot;file&quot;:&quot;entity-framework/82&quot;,&quot;line&quot;:&quot;InvalidInlineCodeSnippet&quot;,&quot;date_time&quot;:&quot;2017-06-13T19:09:36.2776488Z&quot;,&quot;message_severity&quot;:&quot;warning&quot;}

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C13%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201706131909064767-413%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by caleblloyd** [comment]
@SapientGuardian want to check in with you on this first - do you also agree that it would be appropriate to remove the Sapient EF Connector from EF Official Documentation?

**Comment by SapientGuardian** [comment]
:+1: Yes, at this point I don't know of any reason to use it over Pomelo or the official MySql provider.

**Comment by Kagamine** [comment]
@rowanmiller

**Comment by caleblloyd** [comment]
Rowan switched off the EF team

Maybe @divega can help?

**Comment by divega** [comment]
@caleblloyd @Kagamine @SapientGuardian sorry for the delayed response and thanks for the fix.

**Comment by Kagamine** [comment]
:)

**Pull request merged**
