### PR TITLE
Fixed whitespaces to display correctly @ docs.microsoft.com

### PR DESCRIPTION
**Pull request by FabianGosebrink**
https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite was displaying backticks instead of beautiful markdown code

### CODE REVIEW

**Comment by bradygaster** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/FabianGosebrink/EntityFramework.Docs/blob/patch-1/entity-framework/core/get-started/netcore/new-db-sqlite.md) | :warning:Warning | | [Details](#user-content-entity-framework/core/get-started/netcore/new-db-sqlite.md)

<a name="entity-framework/core/get-started/netcore/new-db-sqlite.md"></a>
### [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/FabianGosebrink/EntityFramework.Docs/blob/patch-1/entity-framework/core/get-started/netcore/new-db-sqlite.md)
 - **Line Unspecified**: **[Warning]** internal error: the updated_at is missing

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C10%5Cc1705ea6-142e-cb02-f3b5-8dd98c6d1733%5CPullRequest%5C201611102304037326-299%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by FabianGosebrink** [comment]
Hey @bradygaster ,
thanks for looking into this. How can I fix the issue?

Thanks
Fabian

**Comment by rowanmiller** [comment]
I think that warning is unrelated to this change, I have seen it pop up from time to time - usually when something else fails. I can take a look at this and merge it.

**Comment by rowanmiller** [comment]
@FabianGosebrink can you make this PR against `master` branch, rather than `live`, and I will merge it.

**Comment by FabianGosebrink** [comment]
@rowanmiller just switches to master branch. If I can do anything else please let me know. 
Thank you

Fabian

**Comment by rowanmiller** [comment]
Thanks for the contribution!

**Pull request merged**
